{
 "title": "Traefik",
 "tags": [
  "traefik",
  "system",
  "server",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Code ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(method, code) (rate(traefik_service_requests_total{protocol=\"http\"}[1m])) > 0",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(service) (rate(traefik_service_requests_total[$__rate_interval]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Last Reload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_config_last_reload_success * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Config Reload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traefik_config_reloads_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Needs cAdvisor",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"traefik\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Entrypoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_request_duration_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Connections  per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "traefik_open_connections", "legendFormat": "{{entrypoint}}" }
   ]
  },
  { "title": "Routers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Requests per Router",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(router) (rate(traefik_router_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration per Router",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traefik_router_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request size  per Router",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "label_replace(sum by(service) (rate(traefik_service_responses_bytes_total[$__rate_interval])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Certificate Dates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "traefik_tls_certs_not_after{san=~\".*\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Type chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(tls_version) (rate(traefik_entrypoint_requests_tls_total[$__rate_interval]))",
     "legendFormat": "TLS {{tls_version}}"
    }
   ]
  },
  {
   "title": "TLS Cipher chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(tls_cipher) (rate(traefik_entrypoint_requests_tls_total[$__rate_interval]))",
     "legendFormat": "{{tls_cipher}}"
    }
   ]
  },
  { "title": "HTTP Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "2xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method, code) (rate(traefik_service_requests_total{code=~\"2..\", protocol=\"http\"}[5m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "5xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method, code) (rate(traefik_service_requests_total{code=~\"5..\", protocol=\"http\"}[5m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Other codes over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method, code) (rate(traefik_service_requests_total{code!~\"2..|5..\", protocol=\"http\"}[5m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method) (rate(traefik_service_requests_bytes_total{protocol=\"http\"}[1m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method) (rate(traefik_service_responses_bytes_total{protocol=\"http\"}[1m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "HTTP 404 Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{filename=\"/treafik/access.log\"} | json | OriginStatus = `404`"
    }
   ]
  },
  {
   "title": "HTTP 403",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "{filename=\"/treafik/access.log\"} |= `` | json | OriginStatus = `403`"
    }
   ]
  },
  {
   "title": "Traefik Error Level",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{filename=\"/treafik/traefik.log\"} | json | level = `error`"
    }
   ]
  }
 ]
}