{
 "title": "VyOS Router Metrics",
 "description": "VyOS Router Metrics",
 "tags": [
  "vyos",
  "metrics",
  "network",
  "router"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "router", "label": "Router", "query": { "query": "label_values(router)" } },
   {
    "name": "devices",
    "label": "Interfaces",
    "query": {
     "query": "label_values(node_network_carrier,device)"
    }
   },
   { "name": "endpoint", "label": "endpoint", "query": { "query": "label_values(endpoint)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{router=~\"$router\"} - node_boot_time_seconds{router=~\"$router\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{router=~\"$router\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode!=\"idle\", router=~\"$router\"}[$__rate_interval]) * 100)) / (scalar(count(node_cpu_seconds_total{mode=\"user\", router=~\"$router\"})))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{router=~\"$router\"} / node_memory_MemTotal_bytes{router=~\"$router\"}) * 100"
    }
   ]
  },
  {
   "title": "NAT Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{router=~\"$router\"}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"$devices\", router=~\"$router\"}[$__rate_interval])) + (sum(rate(node_network_transmit_bytes_total{device=~\"$devices\", router=~\"$router\"}[$__rate_interval])))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Free Storage Root",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_free_bytes{router=~\"$router\", mountpoint=\"/boot\"}) / sum(node_filesystem_size_bytes{router=~\"$router\", mountpoint=\"/boot\"})) * 100"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{router=~\"$router\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{router=~\"$router\", device=~\"$devices\"}[$__rate_interval])",
       "legendFormat": "In: {{ device }}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{router=~\"$router\", device=~\"$devices\"}[$__rate_interval])",
       "legendFormat": "Out: {{ device }}"
      }
     ]
    },
    {
     "title": "Softnet Dropped Packets (CPU Overload)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_softnet_dropped_total{router=~\"$router\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{router=~\"$router\"}",
       "legendFormat": "Current Connections"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{router=~\"$router\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "NAT / Connection Tracking Statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_nf_conntrack_stat_drop{router=~\"$router\"}[$__rate_interval])",
       "legendFormat": "Dropped Packets"
      },
      {
       "expr": "rate(node_nf_conntrack_stat_invalid{router=~\"$router\"}[$__rate_interval])",
       "legendFormat": "Invalid Packets"
      },
      {
       "expr": "rate(node_nf_conntrack_stat_insert_failed{router=~\"$router\"}[$__rate_interval])",
       "legendFormat": "Insert Failed"
      },
      {
       "expr": "rate(node_nf_conntrack_stat_early_drop{router=~\"$router\"}[$__rate_interval])",
       "legendFormat": "Early Drops (Table Full)"
      },
      {
       "expr": "rate(node_nf_conntrack_stat_search_restart{router=~\"$router\"}[$__rate_interval])",
       "legendFormat": "Search Restarts"
      }
     ]
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "repeat": "endpoint",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(phase) (probe_icmp_duration_seconds{router=~\"$router\", phase!=\"setup\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Network Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device) (irate(node_network_receive_packets_total{router=~\"$router\", device=~\"$devices\"}[5m]))",
     "legendFormat": "{{device}} - Rx"
    },
    {
     "expr": "sum by(device) (irate(node_network_transmit_packets_total{router=~\"$router\", device=~\"$devices\"}[5m]))",
     "legendFormat": "{{device}} - Tx"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{router=~\"$router\", device=~\"$devices\"}[$__rate_interval])",
     "legendFormat": "RX Errors: {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{router=~\"$router\", device=~\"$devices\"}[$__rate_interval]) * -1",
     "legendFormat": "TX Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "Network Traffic Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{router=~\"$router\", device=~\"$devices\"}[$__rate_interval])",
     "legendFormat": "RX Drops: {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{router=~\"$router\", device=~\"$devices\"}[$__rate_interval]) * -1",
     "legendFormat": "TX Drops: {{ device }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(mode) (rate(node_cpu_seconds_total{mode!=\"idle\", router=~\"$router\"}[$__rate_interval]) * 100)) / (scalar(count(node_cpu_seconds_total{mode=\"user\", router=~\"$router\"})))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{router=~\"$router\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{router=~\"$router\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{router=~\"$router\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{router=~\"$router\"} - (node_memory_MemFree_bytes{router=~\"$router\"} + node_memory_Buffers_bytes{router=~\"$router\"} + node_memory_Cached_bytes{router=~\"$router\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{router=~\"$router\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{router=~\"$router\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{router=~\"$router\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{router=~\"$router\", mountpoint=\"/boot\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{router=~\"$router\", mountpoint=\"/boot\"} - node_filesystem_free_bytes{router=~\"$router\", mountpoint=\"/boot\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}