{
 "title": "Tailscale",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "All stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subnet Router",
   "type": "stat",
   "description": "Advertised and approved subnet routes",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_advertised_routes{instance=~\"$instance\"}",
     "legendFormat": "Advertised Routes"
    },
    {
     "expr": "tailscaled_approved_routes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_health_messages{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Traffic Summary per path",
   "type": "timeseries",
   "description": "Inbound/outbound bytes/sec per path",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(path) (irate(tailscaled_inbound_bytes_total[2m])) * 8",
     "legendFormat": "{{path}} - Receive"
    },
    {
     "expr": "sum by(path) (irate(tailscaled_outbound_bytes_total[2m])) * 8",
     "legendFormat": "{{path}} - Transmit"
    }
   ]
  },
  { "title": "Total Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Traffic Summary inbound ",
   "type": "timeseries",
   "description": "Inboundbytes/sec per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(tailscaled_inbound_bytes_total{instance=~\"$instance\", path=~\"direct_.*\"}[2m])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Traffic Summary Outbound",
   "type": "timeseries",
   "description": "Outbound bytes/sec per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(tailscaled_outbound_bytes_total{instance=~\"$instance\", path=~\"direct_.*\"}[2m])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Direct Traffic (P2P)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Inbound",
   "type": "timeseries",
   "description": "Traffic from direct peer-to-peer connections.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(tailscaled_inbound_bytes_total{instance=~\"$instance\", path=~\"direct_.*\"}[2m]))*8",
     "legendFormat": "{{instance}} RX {{path}}"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "timeseries",
   "description": "Traffic to direct peer-to-peer connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(tailscaled_outbound_bytes_total{instance=~\"$instance\", path=~\"direct_.*\"}[2m]))*8",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  },
  {
   "title": "Relayed Traffic (DERP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound",
     "type": "timeseries",
     "description": "Traffic from relayed connections. DERP (Designated Encrypted Relay for Packets) servers act as a relay server when a direct connection isn’t possible. Relay connections might result in higher latency.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(tailscaled_inbound_bytes_total{instance=~\"$instance\", path=\"derp\"}[2m])*8",
       "legendFormat": "{{instance}} RX {{path}}"
      }
     ]
    },
    {
     "title": "Outbound",
     "type": "timeseries",
     "description": "Traffic from relayed connections. DERP (Designated Encrypted Relay for Packets) servers act as a relay server when a direct connection isn’t possible.  Relay connections might result in higher latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(tailscaled_outbound_bytes_total{instance=~\"$instance\", path=\"derp\"}[2m])*8",
       "legendFormat": "{{instance}} TX {{path}}"
      }
     ]
    }
   ]
  }
 ]
}