{
 "title": "Cloudflare Tunnels",
 "tags": [
  "server",
  "system",
  "clouldflare tunnels"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "conn_index", "query": { "query": "label_values(conn_index)" } }
  ]
 },
 "panels": [
  {
   "title": "Connected HA Edge",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_server_locations > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number HA Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(conn_index) (quic_client_latest_rtt)",
     "legendFormat": "Edge ID {{conn_index}}"
    }
   ]
  },
  {
   "title": "Bandwidth ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(quic_client_receive_bytes[$__rate_interval]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum by(instance) (rate(quic_client_sent_bytes[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "TCP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "cloudflared_tcp_active_sessions",
     "legendFormat": "Active Sessions"
    },
    {
     "expr": "rate(cloudflared_tcp_total_sessions[$__rate_interval])",
     "legendFormat": "Total Sessions"
    }
   ]
  },
  {
   "title": "UDP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "cloudflared_udp_active_sessions",
     "legendFormat": "Active Sessions"
    },
    {
     "expr": "rate(cloudflared_udp_total_sessions[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(quic_client_closed_connections[$__rate_interval])",
     "legendFormat": "Closed Connections"
    }
   ]
  },
  {
   "title": "Errors  Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_request_errors[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel",
     "legendFormat": "Concurrent  requests"
    }
   ]
  },
  {
   "title": "Total  Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_total_requests[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Packets to Big",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(quic_client_packet_too_big_dropped[$__rate_interval])",
     "legendFormat": "Packets to Big"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_active_streams",
     "legendFormat": "Active Streams"
    }
   ]
  },
  { "title": "RTT - Latency (Per Edge)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Edge ID  $conn_index",
   "type": "timeseries",
   "description": "Edge ID matches with the ID in the table in the first row.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "repeat": "conn_index",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quic_client_latest_rtt{conn_index=~\"$conn_index\"}",
     "legendFormat": "Latest"
    },
    {
     "expr": "quic_client_min_rtt{conn_index=~\"$conn_index\"}",
     "legendFormat": "Minimum"
    },
    {
     "expr": "quic_client_smoothed_rtt{conn_index=~\"$conn_index\"}",
     "legendFormat": "Smoothed"
    }
   ]
  },
  { "title": "Quic Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Edge $conn_index",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "repeat": "conn_index",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(quic_client_receive_bytes{conn_index=~\"$conn_index\"}[$__rate_interval])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(quic_client_sent_bytes{conn_index=~\"$conn_index\"}[$__rate_interval])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}