{
 "title": "Cloudflare Tunnels",
 "tags": [
  "server",
  "system",
  "clouldflare tunnels"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "conn_index", "query": { "query": "label_values(conn_index)" } }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Configuration version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_orchestration_config_version",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel Registrations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_tunnel_register_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected HA Edge",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_server_locations",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number HA Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Configuration Pushes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_config_local_config_pushes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Config Error Pushes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_config_local_config_pushes_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "TCP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cloudflared_tcp_active_sessions",
     "legendFormat": "Active Sessions"
    },
    {
     "expr": "rate(cloudflared_tcp_total_sessions[$__rate_interval])",
     "legendFormat": "Total Sessions"
    }
   ]
  },
  {
   "title": "UDP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cloudflared_udp_active_sessions",
     "legendFormat": "Active Sessions"
    },
    {
     "expr": "rate(cloudflared_udp_total_sessions[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(quic_client_closed_connections[$__rate_interval])",
     "legendFormat": "Closed Connections"
    }
   ]
  },
  {
   "title": "Errors  Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_request_errors[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel",
     "legendFormat": "Concurrent  requests"
    }
   ]
  },
  {
   "title": "Total  Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_total_requests[$__interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Packets to Big",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "rate(quic_client_packet_too_big_dropped[$__rate_interval])",
     "legendFormat": "Packets to Big"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_active_streams",
     "legendFormat": "Active Streams"
    }
   ]
  },
  { "title": "RTT - Latency (Per Edge)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Edge ID  $conn_index",
   "type": "timeseries",
   "description": "Edge ID matches with the ID in the table in the first row.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "repeat": "conn_index",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quic_client_latest_rtt{conn_index=~\"$conn_index\"}",
     "legendFormat": "Latest"
    },
    {
     "expr": "quic_client_min_rtt{conn_index=~\"$conn_index\"}",
     "legendFormat": "Minimum"
    },
    {
     "expr": "quic_client_smoothed_rtt{conn_index=~\"$conn_index\"}",
     "legendFormat": "Smoothed"
    }
   ]
  },
  { "title": "Bandwidth  (Per Edge)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Edge ID $conn_index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "repeat": "conn_index",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(quic_client_receive_bytes{conn_index=~\"$conn_index\"}[$__rate_interval])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(quic_client_sent_bytes{conn_index=~\"$conn_index\"}[$__rate_interval])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}